### ISSUE TITLE
Doesn't work or not sure how to use

### ISSUE THREAD

**Issue by NRschwier** [jeremiahverba/qss#1]
Hello,

I really like your idea but it doesnt seem to work. I click on the condition icon on a token and nothing happens, there is no dialogue or fext field for filtering conditions. Am I using this wrong? or should that work?

**Comment by jeremiahverba** [comment]
Seems like something is wrong.  If you left click a token, then right click
it, then left click the icon to the right of the token you get nothing?

**Comment by jeremiahverba** [comment]
I wonder if it's a compatibility issue.  Could you share your console log here?  Or at least give me a list of the modules you have installed?

**Comment by NRschwier** [comment]
Hello!

Thank you for your response, here is the error in the console
[image: image.png]

**Comment by jeremiahverba** [comment]
I'm not seeing the attached file.

**Comment by NRschwier** [comment]
Oh strange, lets try this.

**Comment by arbron** [comment]
Not sure if you are having the same issue, but I was getting a `GET https://.../modules/quick-status-select/scripts/log.js net::ERR_BLOCKED_BY_CLIENT` error because my browser thinks `log.js` is a tracker. I was able to fix it by whitelisting my Foundry server to prevent blocking of trackers, but this might be preventing the module from being loaded for anyone who has tracking protection enabled.

**Comment by jeremiahverba** [comment]
@arbron  thanks for the insight.  That script is just a tiny shim for convenient console.log-ing

@NRschwier  There is still no attachment.  Sorry for the delay.  Can you just try copy and pasting the text?  Maybe to a pastebin if it's too long for here.

**Comment by jeremiahverba** [comment]
This should be resolved now. (v.1.4.0)  I made the entire module MUCH simpler.  

This update includes removing that extra log.ts file that should help with tracker blockers.
