### ISSUE TITLE
Support for PF2

### ISSUE THREAD

**Issue by apoapostolov** [jeremiahverba/qss#6]
Your mod is amazing, but it seems to work for 5E only. PF2 has its own implementation of conditions but it is very similar and it should be possible to have filtered list for it as well. Currently, it overrides the window but shows nothing (not even the filter field).

**Comment by jeremiahverba** [comment]
Interesting.  I personally have only tested it on 5E.  I will check it out for PF2 and see what I didn't hook up correctly.

**Comment by jeremiahverba** [comment]
This should be fixed in 1.3.0 !

It's a slightly more basic implementation, where it no longer has the long list of conditions, but instead just uses the search input to highlight the buttons in the default selection grid.  This is because of how PF2E's game system does conditions.  They are much more complicated than DND5E's.  I didn't want to interfere with how they work.

If you have trouble updating, uninstall /reinstall or use this manifest url to install:
https://raw.githubusercontent.com/jeremiahverba/qss/main/src/module.json
